/*
 * File: app/model/Marker.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Roadpech.model.Marker', {
    extend: 'Ext.data.Model',

    config: {
        mapMarker: '',
        identifier: 'sequential',
        fields: [
            {
                name: 'id',
                type: 'auto'
            },
            {
                name: 'time_stamp'
            },
            {
                defaultValue: 3,
                name: 'traffic_level',
                type: 'int'
            },
            {
                name: 'lat'
            },
            {
                name: 'lng'
            },
            {
                defaultValue: 1,
                name: 'usercount'
            }
        ]
    },

    updateMapMarker: function(options) {
        if (this.id){
            var me = this,
                marker = this.getMapMarker(),
                traffic_level = me.get('traffic_level'),
                colour = (this.phantom) ?  "69FE96" : "FE7569";

            if (marker)
            marker.setIcon("http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld="+traffic_level+"|"+colour);
        }
    },

    setTrafficLevel: function(traffic) {
        this.set('traffic_level', traffic);
        console.log(traffic);
        this.updateMapMarker();
    },

    setLocation: function(latlng) {
        if (latlng){
            this.set('lat', latlng.lat());
            this.set('lng', latlng.lng());
        }else{
            console.log(latlng);
        }
    }

});