/*
 * File: app/controller/MainController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Roadpech.controller.MainController', {
    extend: 'Ext.app.Controller',

    config: {
        views: [
            'Main'
        ],

        routes: {
            'map': 'viewMap'
        },

        refs: {
            mainView: {
                autoCreate: true,
                selector: 'mainView',
                xtype: 'mainView'
            }
        }
    },

    viewMap: function() {
        var mainView = this.getMainView();
        mainView.setActiveItem(0);
        Ext.Viewport.setActiveItem(mainView);
    }

});